app: course-policy-ai
plugins:
  - serverless-offline
  - serverless-plugin-utils
org: coursepolicy
service: core

frameworkVersion: '3'
custom:
  stage: ${opt:stage, self:provider.stage}
  defaultStage: staging
  ssm:
    QUALTRICS_API_TOKEN: ${ssm:qualtrics-api-token}
    SURVEY_ID: ${ssm:survey-id}
    DATABASE_URL: ${ssm:db-url}
    CORE_BASE_URL: ${ssm:core-base-url}
    DATABASE_PASSWORD: ${ssm:survey-db-password}
    DATABASE_USERNAME: ${ssm:survey-db-username}
    DATABASE_NAME: ${ssm:survey-db-name}
    DATABASE_HOST: ${ssm:survey-db-host}
    DATABASE_PORT: ${ssm:survey-db-port}

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  stage: ${opt:stage, self:custom.defaultStage}
  httpApi:
    cors: true
  apiGateway:
    binaryMediaTypes:
      - 'application/pdf'
    metrics: true
  logs:
    restApi: true
  environment: ${self:custom.ssm, file(./serverless/${opt:stage}.env.json)}

functions:
  postPolicyWebhook:
    handler: dist/src/http/post-policy-webhook/index.handler
    events:
      - httpApi:
          path: /hook
          method: post
  getPolicy:
    handler: dist/src/http/get-policy/index.handler
    events:
      - httpApi:
          path: /policy
          method: get
    timeout: 30
  updatePolicy:
    handler: dist/src/http/update-policy/index.handler
    events:
      - httpApi:
          path: /policy
          method: post
  getGeneratedPdf:
    handler: dist/src/http/get-generated-pdf/index.handler
    events:
      - httpApi:
          path: /generated-pdf
          method: get
    timeout: 180
    memorySize: 2048
    layers:
      - arn:aws:lambda:us-west-2:${ternary( ${self:custom.stage}, production, 208733872559, 694509587593)}:layer:chromium:${ternary( ${self:custom.stage}, production, 1, 3)}
